ssrando/ssrando

SS Rando Logic - Item Location.yaml
SS Rando Logic - Macros.yaml
logic/logic.py
ssrando.py

It looks like Crystals are still broken though. 5 packs don't appear in the spoiler log and I've never seen Batreaux have progress except for 5 and 10 crystals checks.

Put Key Pieces and Crystals earlier in logic

---

SS Rando Logic - Item Location.yaml
SS Rando Logic - Macros.yaml
eventpatches.yaml
gamepatches.py
patches.yaml

- Ancient Sea Chart unlocks Ship Dowsing
- Removed talk triggers from Mogmas in Skyview 2 (except the first one)
- Removed Fi Text in front of LMF Boss Door
- Removed a soil patch in the tree eye room of Skyview 2 that can block the box

Various changes

---

randogui.py
randogui.ui
ui_randogui.py

Changelog:
- Added Permalink UI component, which updates when settings are changed and can synchronize the options when manually changed
- Added a help text when hovering over options
- Fixed some layouts

UI updates

---

README.md
SS Rando Logic - Item Location.yaml
SS Rando Logic - Macros.yaml
logic/constants.py
options.py
patches.yaml
randogui.py
randomizer-changes.md
ui_randogui.py

I accidently did all of what the title suggests on top of the base with all the fi text skips (my other PR), so be careful

Added Hero Mode option, normal mode logic, split sidequest category

---

SS Rando Logic - Item Location.yaml

ANother goddess chest typo

---

SS Rando Logic - Glitched Requirements.yaml
SS Rando Logic - Glitchless Requirements.yaml
checks.yaml
patches.yaml

Added two new checks to Volcano Summit:
- Small chest in front of sword in Boko Base
- Boko Base pouch chest

Added two new checks to Volcano Summit

---

ssrando.py

Advanced song hints used the original trial to determine if it is WotH rather than the randomized trial

Fixed advanced song hints with trial rando

---

gui/randogui.ui
gui/ui_randogui.py
logic/constants.py
logic/hints.py
logic/logic.py
options.yaml

Added an option for forcing a sword to appear at the end of a required dungeon, if possible.

Sword Dungeon Reward

---

options.yaml
randoscript.py

Makes for a nicer help, it also has some checking functionality already built in

Use argparse for parsing command line arguments

---

names.txt

Fix typo in hash

---

CHANGELOG.md
logic/hints.py
logic/logic.py
ssrando.py

Part 1 in making hints better, this fixes a critical bug in hint placements and makes barren hints stronger (and adds them to the spoiler log)

Better hints

---

version.py

This also influences the hash, it's designed to guard against racing with changes by accident

Show if the working tree is dirty in version

---

gui/randogui.py
options.py

this allows to keep settings even if new are added, saves cosmetic settings too

save settings as dict

---

eventpatches.yaml
patches.yaml

Shortens/removes various other cutscenes in dungeons or side quests

Cutscene skips

---

hints/hint_distribution.py

Remove while loops in hint_distribution.py

---

CHANGELOG.md
eventpatches.yaml

The flow is pretty confusing, so this needs a bit of testing.

fix gorko asking for bombs without having bomb bag

---

CHANGELOG.md
SS Rando Logic - Glitched Requirements.yaml
SS Rando Logic - Glitchless Requirements.yaml
eventpatches.yaml
gamepatches.py
logic/logic.py
patches.yaml

Preparation for ER to get rid of the concept of "dungeon inside dungeon" (which doesn't make sense with full ER)

make ToT always layer 2, locate machi after SV, unlock endurance potion with raising LMF

---

checks.yaml

Adds the following sometimes hints
- Great Tree
- SV Dig Spot
- Turf Slide
- Slope Boulder Dig Spot (2x20)
- ET West Wing
- Fire Node Shortcut
- Lightning Node Ending
- Floria Chest
- AC East Wing
- SSH Brig Key

Add additional sometimes hints

---

patches.yaml

And some minor cleanup of the code

Removes Wryna Requirement in Parrow's House

---

patches.yaml

More arrow drops

---

patches.yaml

This was intended to be part of a bigger text patch PR but I couldn't think of anything else. Wanted to get this in in time for Season 2 though.

remove the first part of bertie's text

---

patches.yaml

Removes Boulder cs in Lanayru

---

CHANGELOG.md
gamepatches.py
sslib/allpatch.py

also move object patch patching to the patcher
https://nightly.link/lepelog/ssrando/workflows/build.yaml/stage-arc-replace/dist%20windows-latest

make arc-replacements work for oarc in stages as well

---

CHANGELOG.md
hints/distributions/README.md
hints/distributions/sample.json
hints/hint_distribution.py

Added hints that point to the location of the boss key for required dungeons

Boss key hints

---

patches.yaml

removed SG temple first time entering cs
removed SG big door cs
moved first eye in sykview to all layers
added 2 bomb pots in Faron (near entrance statue, and near VP)
added arrow pot in AC (near entrance statue)
Give 5 beacons from the start
remove 5 beacon cs

QoL changes

---

CHANGELOG.md
SS Rando Logic - Glitched Requirements.yaml
SS Rando Logic - Glitchless Requirements.yaml
checks.yaml
logic/constants.py
logic/logic.py
names.txt
options.yaml
randomizer-changes.md

changed the name Molderach to the correct name Moldarach everywere

fix Moldarach name

---

asm/sources/IoSGodCrest.cpp
asm/sources/common.h
asm/sources/erFixes.cpp
asm/sources/startFlags.cpp

wanted to do that for a while, this is just for documentation and nothing else

port asm source from er

---

hints/hint_distribution.py
logic/logic.py

fix always unrequired sky keep

Triforce fixes

---

eventpatches.yaml
gamepatches.py
gui/randogui.ui
gui/ui_randogui.py
options.yaml
patches.yaml

Option currently set as default needs ui implementation
- ItemGet for whitesword changed when haveing Option set 
- Starting sword equal or higher then whitesword now actually gives the extra dowsing slots
- If option is set also sets dowsings when haveing Starting sword equal or higher then whitesword

Get all new Dowsing Options after getting Whitesword

---

patches.yaml

Removes the first time textbox when picking up deku seeds.

Remove first time text for deku seeds

---

checks.yaml

Make Lanayru SotH check a fetch quest

---

gui/randogui.py
gui/randogui.ui
gui/sort_model.py
gui/ui_randogui.py
logic/logic.py
options.py
options.yaml

UI isn't currently the greatest for this but it will be addressed with the remainder of the UI changes

Exclude Individual Locations

---

SS Rando Logic - Glitched Requirements.yaml
SS Rando Logic - Glitchless Requirements.yaml
checks.yaml

Updates the old logic files for use by the tracker while the development of new logic parsing takes place. Updates all the checks to use the new names (e.g. Knight Academy --> Upper Skyloft) and adds the new Bokoblin Base checks.
Also updates the order of the checks in `checks.yaml` so that the rupeesanity checks will show up in a meaningful order on the tracker (currently, they are bunched together and often not in the order in which you would get them when playing the game).

Update old logic files for tracker

---

SS Rando Logic - Glitched Requirements.yaml
SS Rando Logic - Glitchless Requirements.yaml

Updates the weird Queetle logic in the old logic files where upgrading Heetle was a logical alternative to finding a 3rd Beetle.

Update Queetle in old logic files

---

gamepatches.py
sslib/allpatch.py

this fixes issues when there are big models added from previous runs, since they weren't removed previously
Kinda jank

always patch layers that can be modified

---

gui/randogui.py
gui/ui_randogui.py

Adds the seed and error message to error messages displayed by the GUI whenever they are available. Closes #117.

Add Seed and Permalink to Error Messages when they Exist

---

checks.yaml

Fixes the mis-worded hint text bug

Fix "They say that They say that" hint text bug

---

README.md
randomize.bat

Updates some misc things to use/reference `pdm`

Update old references to requirements.txt files

---

SS Rando Logic - Glitched Requirements.yaml
SS Rando Logic - Glitchless Requirements.yaml
checks.yaml
logic/requirements/Sky.yaml
options.yaml

Fixes the name of one of the goddess chests I noticed during a co-op seed

Fix name for one of the goddess chest

---

logic/randomize.py

Removes error when starting with all items and have the random start item option enabled

Fix error with random starting item

---

patches.yaml

To Test:
- all combinations of g3 skip enabled/disabled and horde skip enabled/disabled

fix skip-g3 when skip-horde is enabled

---

gamepatches.py

Shhhh, you didn't see anything :p

Fix missed bug with change to rupeesanity option

---

patches.yaml

Add hotfix for relic shuffle from PR

---

gui/dialogs/progressbar/progressdialog.py

Tips for how to enter FFW and Boko Base, and how to end Pumpkin Archery early.

Add more tips to the progress dialog

---

randoscript.py
ssrando.py

fix placement file

---

checks.yaml

Fix crystal quests not appearing under the correct select filter

---

asm/custom-functions/src/lib.rs
asm/original_symbols.txt

printf is a variadic function, that can take a flexible amount of parameters, corresponding to the amount of placeholders in the format string
no change in behaviour

fix printf

---

gui/presets/default_presets.json
logic/randomize.py
options.yaml

Renames the "All Dungeons" DER setting to "All Surface Dungeons" to better describe its behaviour

Rename DER option

---

hints/distributions/Strong Dowsing All Dungeons.json
options.yaml

The AD hint distro that the racing community have been using

Add Strong Dowsing All Dungeons hint distro

---

logic/constants.py

Because there's always something 😔

Fix lone constant used for LMF exit

---

hints/distributions/Co-op S1.json
hints/distributions/README.md
hints/distributions/sample.json
hints/hint_distribution.py

As the title says.
Allows control over whether items are removed for sots/path hints or item hints.

Allow specific hint types for removed items

---

gui/dialogs/tricks/tricks_dialog.ui
gui/dialogs/tricks/ui_tricks_dialog.py

Remove a stray "test" tooltip from the Disabled Tricks area

---

dump.yaml
logic/requirements/Eldin.yaml

As discussed in https://discord.com/channels/767090759773323264/767093096130805811/1196180487987789904

Allow getting the Eldin first Rupee from Eldin East with Beetle

---

options.yaml

For more consistent formatting with other options' help texts.

Add bold formatting to BiT Changes help text

---

.github/ISSUE_TEMPLATE/ISSUE.md
.github/PULL_REQUEST_TEMPLATE.md

Adds templates for github PRs and issues :p

Add github templates

---

SpoilerLog.py
hints/hint_distribution.py
logic/logic_utils.py

Changes the weights for barren hints to only take into account unbanned accessible checks

Better weights for barren hints

---

patches.yaml

Fixes the single eye-locked door in Skyview Temple not working correctly on layer 2.
I genned a seed starting with scale, went to Skyview Temple, and then opened the single eye door :p

Fix single eye in Skyview Temple on layer 2

---

hints/distributions/Fi & Gossip Stones.json
hints/distributions/README.md
hints/hint_distribution.py
options.yaml

As per discussion in https://discord.com/channels/767090759773323264/1193975024936292462

Allow types of hints to be split between Fi and Gossip Stones

---

options.yaml

Fixes a typo and an accidental omission.
I opened the rando gui
/

Fix two errors in option descriptions
