logic/logic.py

I recommend a very serious read before merging.
- I changed how usefulness fractions worked. Now it computes #(locations the items can potentially unlock)/#(minimum number of items needed to unlock a new location with that item)
- I multiplied the weight of dungeon locations by 2 (if you don't like this change, feel free to remove it)
- The exception "Only items left to place are predetermined items at inaccessible locations!" that follows the prerandomized item section of randomize_progress_items() used to be called many times (almost every time when banning many types). I am not completely sure I fixed it right but it doesn't seem to happen anymore (but that's why I would recommend a careful read)
I do not know the dictionnary type very well and may have made things more complicated …

Logic Patch: New Usefulness Fraction computation, Balancing, Error Fixing

---

patches.yaml

Cutscenes deleted:
- Isle of Songs Intro cutscene
- Fi text for deep woods vine
- Initial Fi text in deep woods
- Initial Fi text in Skyview 2
- Cutscene inside Statue in Ancient Cistern
- Generator Fi text for both the Fire Node and the Thunder Node
- Fi text after boss key chest in Sandship
- Fi text after chest in lanayru caves
There's definitely more but we will figure them out while playing more

Various Cutscene Skips

---

patches.yaml

- Start with updated Sand Sea Map (good for casuals to know the sand sea is open)
- Untrigger Fledge on top of academy with bow (to prevent duplicated Fledge)
- Delete Wryna outside skyloft (she's always inside, kind of a duplicate)
- Delete both just sayin' mogmas in front of ET (you can try to talk to them and they have no text so it's weird)
- Delete 3 fi texts in sandship (no more long fi cutscenes after defeating Scervo)

More patches

---

SS Rando Logic - Macros.yaml
eventpatches.yaml
patches.yaml

- Change Stone Tablet Text in Ancient Cistern (it's not "lower" when the statue already is).
- Change Skipper's Event in Stronghold to prevent him showing you where the ship dowsing was in the vanilla game
- Remove all Fi texts in Sky Keep (except the one after the first control panel)
- Remove Beedle's airshop ship intro cutscene
- Remove Lumpy Pumpkin intro cutscene
- Remove cutscene in hub room in Skyview 1
- Remove cutscene showing boss key chest in Ancient Cistern, near AC bokoblin
- Remove all Goron texts in FS Entrance except the first one (Suggestion: make him appear after Goddess White Sword so that getting Goddess Cube dowsing doesn't look weird?)
- Remove short camera pan in first magmanos room in FS
- Delete mogma mitts tutorial in underground section
- Remove Fi Text for …

Various Cutscene Skips 2

---

patches.yaml

Very small pull request. Cutscene Skipped:
- First time talking to Skipper (it is now very short, just like if you've already talked to him before)
- Fi text near waking water in the Faron Silent Realm
- Camera pan cutscene for the bottom water spout inside the AC statue
- Camera pan near the hole after mogma mitts in FS

Various Cutscene Skips 3

---

SS Rando Logic - Item Location.yaml
logic/constants.py
randogui.py
randogui.ui
ui_randogui.py

Here's a semi detailed breakdown of the changes, look at the code for all the details
Added the following types:
- Skyloft
- Sky
- Thunderhead
- Faron
- Eldin
- Lanayru
- Mini Dungeons
- Free Gifts
- Free Standing Items
- Miscellaneous
- Digging Spots
- Bombable Walls
- Combat Rewards
- Songs
- Spiral Charge Chests
- Short Quests
- Long Quests
- Fetch Quests
- Crystal Quests
Removed the following types:
- Short Sidequests
- Main Quest
- Overworld
Reworked Goddess Cube Options
- Can still be enabled/disabled as a whole
- Can be enabled/disabled on a region by region basis
- Each region is split into 2, the main region (usually containing 6 cubes) and the late game region (usually containing 3)
- Regions are: Faron (7) and Lake Floria (2), Eldin (6) and Volcano Summit (3), and Lanayru (6 …

More options

---

gamepatches.py

If you had arcs in the arc-replacement folder that weren't in the ObjectPack, it would error before but shouldn't error now

Fix objectpack patch

---

options.yaml

Add forgotten tricks in Ancient Cistern
(there may be a naming debate because I kept the original "Map Chest Jump" name, to be discussed)

Forgotten-tricks

---

hints/hint_distribution.py

Fixes 3 problems:
- sword rewards being hintable as item, SotS, and random hints.
- item hints being semi-deterministic under specific conditions
- fixed sometimes hints generating barren hints
As a side effect, these changes also prevents the locations of small keys, boss keys, and single crystals from being hinted, outside of an always hint, which in turn prevents Skyloft regions from being SotS hinted for single crystals. It also is likely to decrease the frequency with which sometimes hints are successfully placed. It's possible that this may have unintended consequences for future plando implementations, but we can handle that with the plandos themselves.

Hints Hotfixes

---

CHANGELOG.md
checks.yaml
gui/randogui.ui
gui/ui_randogui.py
hints/hint_distribution.py
hints/hint_types.py
logic/constants.py
logic/logic.py
options.yaml

Change the interaction such that barren hints factor their goddess cubes in as well and sots hints pointing to goddess chests display the zone of the associated cube instead of the chest. Also adds an option for modifying the sots hint to say it involves a cube.

Rework cube hints & add item location/zone switch

---

CHANGELOG.md
hints/hint_distribution.py
hints/hint_types.py

also change all hints that hint an item at a specific location to use the same format
make type more specific for location hints
remove special text coloring from junk hints

fix hint coloring for location hints

---

SS Rando Logic - Glitched Requirements.yaml
SS Rando Logic - Glitchless Requirements.yaml
checks.yaml
patches.yaml

Adds a new chest in the goddess statue corresponding with the vanilla Emerald Tablet location. Also renames the check `Chest Inside Goddess Statue` to allow both checks to exist

Add Emerald Tablet Chest

---

hints/hint_distribution.py
logic/logic.py

**This is a critical S2 fix**
This fixes a bug that causes items that have restricted placements to be unable to be hinted by any type of hint besides always. Currently this only affects maps, small keys, and big keys, however it can be expanded for any other items that my be placed under restrictions in the future. This does not impact fully pre-randomized items such as swords at the end of dungeons in the sword reward mode.
This does have a slight side effect - if for whatever reason keys a fully pre-randomized manually by a code edit, they are still eligible to be hinted, which is contrary to the expected behavior. However, there is no way to tell the difference between an item that was pre-randomized directly and one that placed in the early randomization passes

Fix items shuffled with any restrictions being unable to be hinted

---

SS Rando Logic - Glitched Requirements.yaml
SS Rando Logic - Glitchless Requirements.yaml
checks.yaml
eventpatches.yaml

Adds a text option when you talk to Kina outside that lets you choose between carrying pumpkins and starting her crystal quest. Both can be done independent of each other.

Decouple Kina from Minigames

---

CHANGELOG.md
SS Rando Logic - Glitched Requirements.yaml
SS Rando Logic - Glitchless Requirements.yaml
options.yaml
patches.yaml

Adds option for starting with each of the three subnodes activated, but still needing to activate the main generator to actually raise LMF.

Add main node option for LMF

---

patches.yaml

Because of the removeing of the wyrna requirement there are 2 parrow's at night now until you talk to wyrna for her check. To fix this the parrow before the wyrna's crystals has been removed

Deletes extra Parrow in Parrow's House

---

checks.yaml
hints/distributions/S2 - 2D.json
hints/distributions/S2 - 3D EUD Off.json
hints/distributions/S2 - 3D.json

Final hint distro tweaks before season 2.
Dodoh Crystals has been added as a sometimes hint
Top of LMF hint has been removed for redundancy (all settings have open LMF)
Slingshot hint has been removed to avoid unhinted Owlan Crystals w/ barren slingshot situations.
Some tweaks made to distributions (removing one fixed item and sometimes from each, weakening slightly with weights)

remove slingshot/top of lmf, add dodoh, balancing

---

eventpatches.yaml
patches.yaml

Sets now the correct flag after finishing the bokoblins and thus allos to remove the fi text for real this time.
cs showing off the BK chest in FS has been removed

Fix no fi text before Lopsa roll, remove BK chest cs in FS

---

CHANGELOG.md
gui/randogui.py

This fix isn't elegant but it probably is the *correct* fix. This may also fix similar bugs that haven't been found yet, and should prevent similar bugs from appearing in the future.
When the UI is initialized, default values are loaded in for all options before loading from the settings file (this ensures that even if the settings file is missing or incomplete from a previous version all options are properly initialized). However, because the tricks system is not a 1:1 relationship between the UI and the setting like every other implemented option, the additional processing done on it to populate the UI during loading caused the values stored in the settings file and in working memory to become desynced. Adding a call to synchronize all the settings after the UI has been fully …

Fix Tricks not Reloading From Saved Settings Properly

---

checks.yaml

Fixes the Sandship brig hint to refer to the gratitude of a crew rather than a captain.
Rewords the Great Tree hint so that it doesn't refer to a "hollow tree" (avoids confusion with rupeesanity check names).
Added new hint text for other checks.

Change hint text

---

musicrando.py

It doesn't seem like this has any disadvantages
Leaves the option for now, to be reused for actual custom music support in the near future

always act as if 'allow-custom-music' were checked

---

CHANGELOG.md
patches.yaml

Removes first time textboxes for:
* Green, blue and red Rupees
* Heart flowers
* Arrow drops (singles and bundles)
* Bombs (5 and 10)
* Stamina Fruits
* Silent Realm Tears
* Silent Realm Light Fruits

Remove first time textboxes 2: electric boogaloo

---

patches.yaml

This slightly changes vanilla behaviour, because with this patch the barbed wire only stays gone until you reload via leaving the room, while in vanilla it's always gone after getting the triforce.
However, I don't think this is an issue.
Successfully tested it on console.

fix barbed wire not being gone after obtaining triforce of wisdom check

---

hints/distributions/Balanced.json
hints/distributions/Co-op S1.json
hints/distributions/Junk.json
hints/distributions/S2 - 2D.json
hints/distributions/S2 - 3D EUD Off.json
hints/distributions/S2 - 3D.json
hints/distributions/Weak.json
hints/distributions/sample.json
hints/hint_distribution.py
logic/constants.py
logic/hints.py

Allows hint distributions to specify how many hints should appear on each Gossip Stone. This ranges from 1-8 hints per stone.
Fewer than 1 doesn't make any sense since, if no hints are desired, one can simply use the 'Junk' hint distribution.
More than 8 can result in hints getting cut off from the end of the list when viewed in-game. I suspect that this is due to a character limit but I haven't confirmed this. 8 hints per stone is likely excessive but does provide room to experiment should anyone wish to do so (e.g. having fewer but more valuable hint stones).

n hints per stone

---

logic/randomize.py

Fixes a bug where the players using the same seed that has the `random-starting-item` option enabled may not get the same item. This is due to a use of set comprehension making the random choice result in a potentially different starting item for the same seed.

Fix random starting item not same for all players

---

CHANGELOG.md
eventpatches.yaml
gamepatches.py
patches.yaml

Adds a text sequence onto Fledge's Gift to display the required dungeons for the seed. Additionally displays the same required dungeon text when talking to Fledge again in the Academy corridor.
Removes several panning camera changes during Fledge's Gift.

Remove camera panning during Fledge's Gift

---

CHANGELOG.md
hints/distributions/CDMC.json
options.yaml

Uses the new n hints per stone stuff to only have one hint per stone. Removes a bunch of always and sometimes hints that are easily dowsable and adds a few that aren't.

Add dowsing hint distro

---

asm/linker.ld
asm/original_symbols.txt

no functional changes, but the advantage is that symbols are only defined in `original_symbols.txt` now, and don't need to be defined twice

prune symbols from linker ld

---

asm/patch_diffs/ss_necessary_diff.txt
asm/patches/ss_necessary.asm

Fixes bug where the Goddess Sword wouldn't appear in the Sword Pedestal after getting the Goddess Sword from another check in the game first. This was due to the pedestal actor still having a check for the vanilla Goddess Sword story flag.

Fix bug where sword didn't appear in the pedestal

---

patches.yaml

Fixes an issue where re-entering the Fire Dragon's Lair from the post-boko base VS layer would put Link on F211 layer 0 without a loadzone to exit again. Resolves the issue that Fireworkspinner encountered in a co-op race on 2023-01-18.

Fix bug with Fire Dragon's Lair loadzone

---

CHANGELOG.md
SS Rando Logic - Glitched Requirements.yaml
SS Rando Logic - Glitchless Requirements.yaml
checks.yaml
hints/distributions/S2 - 2D.json
hints/distributions/S2 - 3D EUD Off.json
hints/distributions/S2 - 3D.json
logic/randomize.py
logic/requirements/Faron.yaml
logic/requirements/Sky.yaml

Essentially reverts #317 in favor of removing the inlined requirement for Dodoh. Slingshot seemed to be unrelated, and more related to its name, so it was renamed to Kikwi Elder's Reward. Should also fix nonprogress item calculation and the excluded locations sometimes having progress bug.

fix broken banned locations, rename slingshot

---

gamepatches.py
musicrando.py
options.py
util/file_accessor.py
yaml_files.py

Fixes an issue when running the randomizer on Windows with a system character set that's not UTF-8 (or other anglocentric character set) that meant the yaml files couldn't be read correctly.

Fix stupid windows file encoding stuff

---

options.yaml

Changes the default values for several settings. These include:
* Starting tablets: 3 --> 1 (to match standard settings)
* EUD: off --> on
* Triforce shuffle: Vanilla --> Anywhere
* Max Batreaux: 80 --> 50
* Place Scrap Shop Upgrades: false --> true
* GoT Sword Requirement: MS --> TMS
* Open LMF: Nodes --> Open
* Map mode: unrestricted --> restricted (to match small keys)
* Upgraded Skyward Strike: false --> true
* Starting Items: + dungeon maps
* Excluded Locations: + all cubes, all minigames and Peatrice

Update default options

---

gui/randogui.py
gui/randogui.ui
gui/sort_model.py
gui/tricks_dialog.py
gui/tricks_dialog.ui
gui/ui_randogui.py
gui/ui_tricks_dialog.py
options.yaml
pyproject.toml

Improves the Logic tab of the randomizer. Makes the following changes
- Tricks are migrated to a popup window and removed from the rest of the tab
- Include/Exclude locations have been expanded to fill the vacated space
- Adds a free text search to both the included and excluded locations lists
- Text searches can be done independently on both views and do not impact each other
- Moving an item from to a destination view where the search would hide it is supported (item will be hidden by default)
- Searches are case insensitive, and will match any check name containing the string. It is not limited to word boundaries or any other related limitation
- The serialization process for **all** ListViews has been altered
- Sorting is correctly applied to all ListViews whenever they have an item …

Logic Tab Improvements - Tricks Dialog and Free Text Search

---

asm/assemble.py
asm/patcher.py
gamepatches.py
logic/assumed_fill.py
logic/constants.py
logic/front_fill.py
logic/hints.py
logic/inventory.py
logic/logic.py
logic/logic_expression.py
logic/logic_input.py
logic/logic_utils.py
logic/placement_file.py
logic/random_fill.py
logic/randomize.py
musicrando.py
options.py
sslib/allpatch.py
sslib/dol.py
sslib/fs_helpers.py
sslib/msb.py
sslib/rel.py
sslib/u8file.py
ssrando.py
witmanager.py

Updates some error messages to more clearly describe what went wrong. In particular, the text for not being able to place an item or a hint has been updated to indicate that this might be because the settings are too restrictive and to try randomizing a new seed.
Also standardizes the error messages to start with a capital letter (unless the msg starts with a variable name or similar) and end with a full stop.

Clearer could not place error msgs

---

SS Rando Logic - Glitchless Requirements.yaml

Fixes a bug where the tracker will show Lake Floria as being accessible without Emerald Tablet. This is due to a missing requirement in the old logic files and doesn't impact the actual game logic.

Fix missing old logic emmy requirement for Floria

---

logic/requirements/Eldin.yaml

This also removes an inlined requirement that depended on the Fire Dragon's Reward check (which caused issues when the location is banned).

Remove now-nonexistent exit to Volcano East

---

names.txt

There are now only 4 names not in the textdump:
```
Tricycle
KolokChamp
Scrappa
FunFun
```

fix some hashnames

---

eventpatches.yaml
patches.yaml

Fixes bug were Skipper's "To the Sandship" dialog option opens up after beating Tentalus - even in DER.
Removes extra entrance to SSH after beating Tentalus (causes problems with DER).

Fix Skipper DER Bug

---

patches.yaml

This loading zone was pretty dumb, so now it's appropriately sized.

Enlarge the Thunderhead Loading Zone

---

checks.yaml
gui/components/list_pair.py
gui/dialogs/custom_theme/ui_custom_theme_dialog.py
gui/dialogs/tricks/ui_tricks_dialog.py
gui/models/type_filter_model.py
gui/randogui.py
gui/randogui.ui
gui/ui_randogui.py
logic/constants.py

Adds the ability to add selection based filters to list pairs. This system requires metadata on the composition of the root list in order to function (specifically a mapping of displayed data to type list).
This change includes the addition of select filters for the excluded locations list pair, mimicking a toned down version of banned types from the previous versions of the randomizer. Most types were removed, leaving the following types which are useful either because they can't be text searched or they are an otherwise understandable grouping of checks.
- Goddess Chests
- Faron Woods Goddess Chests
- Lake Floria Goddess Chests
- Eldin Volcano Goddess Chests
- Volcano Summit Goddess Chests
- Lanayru Desert Goddess Chests
- Sand Sea Goddess Chests
- Combat
- Loose Crystals
- Minigames
- …

Select Filters

---

gui/randogui.ui
gui/ui_randogui.py

Got reverted at some point. The tooltips currently show the markdown syntax rather than bolding the relevant text. This fixes that :p

Add back tooltip bold text

---

version.py

That's what the build uses as well

explicitly use 7 characters for the short git version

---

CHANGELOG.md
eventpatches.yaml

Fixes using the unpatched branch, which sets storyflag 20 (which is probably what caused the crash)

fix fire dragon causing sealed grounds crash when both other dragons are met

---

eventpatches.yaml

my previous fix was incomplete, but now it actually directly patches the fire dragon even, so there is no chance of it going to the unpatched flow which doesn't give the item and spits you out near earth temple

actually fix firedragon when both other dragons are met

---

CHANGELOG.md
gamepatches.py
musicrando.py

Adds additional protections to ensure the vanilla tadtones jingle plays when all the Group of Tadtones have been collected.

Prevent Tadtones Jingle Softlock

---

CHANGELOG.md
patches.yaml

Fixes the bug where Fledge wouldn't spawn outside the Sparring Hall when starting with bow. Changed story flag 1114 (Bow text) for 944 (rando flag for obtaining the Bow)

Change story flag for archery Fledge

---

logic/requirements/Skyloft.yaml

This should reallow excluding earlier beedle purchases without errors

Remove Beedle's checks as requirements

---

hints/distributions/2D Dowsing & Fi Hints.json

With dowsing, this chest can be a real pain if you know the bombable wall chest is useless.

Add FS Map chest as sometimes hint to Dowsing Fi Hints

---

hints/hint_distribution.py

Zone should be the normal zone if and only if it's not a cube, not just if separate cube sots is enabled.

Fix incorrect code for cube sots

---

gui/randogui.ui
gui/ui_randogui.py

Rearranges the Completion Conditions, Open Settings, and Shuffles panels on the Randomization Settings tab. This new order should be more user friendly, placing options more users are likely to want to change closer to the "front" (the left side) of the GUI.

Rearrange Panels on Randomization Settings Tab

---

patches.yaml

Makes the item on the gorge pillar no longer rotated at a weird angle

Move gorge pillar item to an upright position

---

hints/distributions/2D Dowsing & Fi Hints.json
hints/hint_distribution.py

This functionality was brought up a while ago but shot down for fear of removing useful dungeon sometimes hints for dungeon boss keys. In my opinion, that case (a dungeon being barren at all + an otherwise useless location hint that would have been placed) is so rare now that it's a non-issue (plus, if this behavior isn't desired, it can be prevented if all sometimes hints come before barren in the hint distribution. I believe it is preferable to prevent otherwise useless sometimes hints from being placed.
The 2D Dowsing & Fi Hints distribution has also been updated to place barren hints before sometimes -- this distro was especially vulnerable to useless sometimes hints given how relatively weak the hint pool is.

Make locations in an already barren-hinted region unhintable

---

gui/randogui.ui
gui/ui_randogui.py
options.yaml

Renames the option "Randomize Starting Location" to "Randomize Starting Spawn". The underlying command name is the same

Rename random starting location

---

hints/distributions/Boss Keysanity Fi Hints.json
options.yaml

This new hint distribution is modeled off the existing Fi hint / chest dowsing-centric distributions, with a few changes tailored to races with boss keysanity enabled, namely...
- The addition of 2 item hints (not really specific to BKsanity, but requested for the new distribution anyway)
- Sandship - Robot in Brig's Reward is an always hint (warranted with the possibility of a no-ping treasure room)
- The old LMF/FS always hints that were removed with dowsing are now sometimes hints - as sometimes a simple ping isn't quite enough information for when to gamble for those checks
- Sandship - Heart Container sometimes hint removed

Add hint distro for bksanity races

---

eventpatches.yaml

that flag was set in the cutscene, that is now removed, so the dungeon wasn't reported as completed in the fi menu

set lmf beaten flag

---

logic/requirements/Ancient Cistern.yaml

Was talked about ages ago but never fixed. Adds scale as a requirement for getting the Whip chest with use of the various AC tricks

Require scale for getting whip chest as a trick

---

gui/dialogs/progressbar/progressdialog.py

Adds a hint to the progressbar explaining some of the swordless movement you can logically be expected to do. Some of the movement (particularly in Pirate Stronghold) is not obvious if you don't already know about it.

Add progressbar tip explaining swordless movement

---

patches.yaml

Doesn't change logic, just a nice QoL change

Add startflag for BtB to Faron Woods log

---

SS Rando Logic - Glitchless Requirements.yaml
entrances.yaml
logic/requirements/Earth Temple.yaml
logic/requirements/Eldin.yaml
logic/requirements/Fire Sanctuary.yaml
logic/requirements/Lanayru Mining Facility.yaml
logic/requirements/Lanayru.yaml
logic/requirements/Skyview.yaml
options.yaml

Updates the logic discussed in the discord server over the last few days.
I also verified what happens with the Pirate Stronghold entrances if you take them without first beating the minidungeon. If you arrive at the ending entrance inside Pirate Stronghold, the door will have bars put up behind you. If you arrive at the ending entrance to the Pirate Stronghold Docks, you are within the Shark Head but you can freely exit through the door you came through.
As a result, I've added a sub-area for Pirate Stronghold and verified what you can do from there

Logic tweaks

---

gui/dialogs/custom_theme/ui_custom_theme_dialog.py
gui/dialogs/tricks/ui_tricks_dialog.py
gui/randogui.ui
gui/ui_randogui.py
hints/hint_distribution.py
logic/logic_input.py
options.yaml
ssrando.py

Adds a cosmetic option to remove the flavor text for location hints.
For example, this turns "a chest atop a sandy retreat" into "Lanayru Sand Sea - Skipper's Retreat - Chest in Shack"

Add Option to De-Obfuscate Location Hints

---

logic/requirements/Eldin.yaml

I started a "Random Starting Entrance" run that spawned me at the Eldin East statue, and my [WIP new logic tracker](https://robojumper.github.io/SS-Randomizer-Tracker/) said that Plat's Gift in Boko Base was in logic. This is because logic thought the entrance was on this side of the rock when it actually was on the other side.
There also appears to be a missing path from First Room to Entry that I added.

Fix some Eldin logic

---

logic/constants.py

Looks like this was missed in #483, resulting in the check being randomized even with Rupeesanity off.

Mark AC Lilypad rupee as a Rupee check

---

gui/randogui.ui
gui/ui_randogui.py
hints/hint_distribution.py
options.yaml

Flips the clear location hints option to cryptic location hints. Default remains false, meaning hints will be clear by default.

Non-cryptic hints by default

---

logic/requirements/Eldin.yaml
logic/requirements/Lanayru.yaml
logic/requirements/Skyloft.yaml

These were found by a simple "unused location" check in the new-logic tracker (area locations that don't correspond to a check and also aren't mentioned in any other expressions). This fixes the ones that very obviously look like bugs -- there are more unused locations but some of them are simply unused in a benign way.

Fix some duplicated locations

---

.github/workflows/dump-check.yaml
README.md
dump.yaml
logic/dump.py
logic/logic_expression.py
logic/logic_input.py
logic/requirements/Lanayru.yaml
randoscript.py

A rebase and continuation of #504.
> Adds dump mode and an automated action to check if the dump file contents in the repository match the contents generated by the randomizer. Failing the dump check does not prevent builds from completing. Dump mode dumps to yaml format.
This dump is currently being used by the [WIP new-logic tracker](https://robojumper.github.io/SS-Randomizer-Tracker/) and it seems to be reasonably complete (with some hardcoding needed for special requirements and logical rules).
The main concern for the future is compatibility - mainly, should this dump format be able to change in an incompatible way due to rando changes or evolutions of the dump format, and if so, when? Should we emit a "spec version" in the dump so that consumers can handle breaking changes? Should …

Logic dump v2

---

logic/hints.py

This is to make sure there are never empty textboxes when talking to a gossip stone

implement fallback junk hints for gossip stones

---

dump.yaml
logic/logic_input.py

* Removes data only relevant to game patches (`room`, `index`, `layer`, ...) from the dump.
* `req_index` is easily reconstructed, as the `items` list in the dump can be inverted to get the requirement index for anything.
* Adds the `original item` key to checks. The immediate use case is that it allows the tracker to compute key semilogic when dungeon keys are not randomized.
This mostly aligns the dump with the [new-logic tracker's](https://robojumper.github.io/SS-Randomizer-Tracker/) type definitions at <https://github.com/robojumper/SS-Randomizer-Tracker/blob/new-logic-tracker/src/logic/UpstreamTypes.ts>. The dump can still be extended of course if there's a good reason for more data but e.g. #525 added more unneeded game data and it's unnecessary churn that makes it harder to review …

Explicitly filter dumped entrance and exit data

---

hints/distributions/Remlits Tournament.json

Adds a small weight to random hints in case of very extreme hint situations on the remlits distribution that could cause seeds to fail.
Ideally in the future we handle this more generally, but in case of no fix in time, this hotfix should work

Hintgen hotfix for tourney

---

options.py

```
Beginner: options ['shopsanity', 'enable-heart-drops', 'starting-heart-pieces', 'fs-lava-flow', 'peatrice-conversations', 'random-start-entrance', 'limit-start-entrance', 'treasuresanity-in-silent-realms', 'trial-treasure-amount', 'random-start-statues'] were reset to default
Allsanity: options ['shopsanity', 'enable-heart-drops', 'starting-heart-pieces', 'fs-lava-flow', 'peatrice-conversations', 'random-start-entrance', 'limit-start-entrance', 'treasuresanity-in-silent-realms', 'trial-treasure-amount', 'random-start-statues'] were reset to default
Remlits: options ['no-spoiler-log', 'random-start-statues'] were reset to default
```

Preset loading: Reset missing options to default

---

asm/custom-functions/src/rando/mod.rs

Just to make things a bit more readable. wchz would also work for automatically zero-terminating the first two, but the last three contain interior NUL wide chars.

Use Wch macro for some constant wide strings

---

patches.yaml

Adds the 2 `ActTag` objects that were added to Faron in the HD remake. These prevent the player's respawn info from being updated. Specifically, this prevents the respawn info from being updated while the player is near or on the fence between Faron and Lake Floria.
I tried voiding out at various points along the fence and specifically tried to replicate the known softlock. I was unable to softlock and Link would respawn in front of the fence each time.
The areas don't cover the outside of the bridge that leads to Lake Floria. It is possible to respawn on the outside of it but not softlock (as far as I know)

Fix Fence Hop Softlock

---

dump.yaml
entrances.yaml
logic/requirements/Faron.yaml

`IV2ISCgBAAAAAAAAgCIgABAgHwAAAAAI+f+HfgAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAANCAAAAAAEAAAA/AGAAADgKQA=#905306` for example errors on main.
`IV2ISCgBAAAAAAAAgCIgABAgHwAAAAAI+f+HfgAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAANCAAAAAAEAAAA/AGAAADgKQA=#166237` is an example of a start in flooded faron.
Also renames some entrances/exits to be consistent with unflooded great tree.
Fixes #514

fix flooded faron woods entrances

---

.github/workflows/build.yaml

Changes the github actions builds from being named "dist windows-latest" to being named "Skyward Sword Randomizer v[version-number-from-pyproject.toml]"
I tested the change on a separate branch to make sure the build artifact was correctly named

Change name of builds from "dist windows-latest"

---

gui/dialogs/progressbar/progressdialog.py
gui/guithreads.py
gui/randogui.py

Previously you could dismiss the progress dialog using ESC while randomization was ongoing, so you could have multiple randomization threads going on at the same time, usually resulting in a corrupt ISO.
This change allows randomization to be cleanly cancelled with a cancel button or the ESC key. This is achieved by throwing an exception in the progress callback after cancellation has been requested, which will fail the randomizer thread. The progress dialog is only ever manually closed by the main GUI thread after randomization has succeeded or failed.
* I tested on Windows
* I tested that the initial extraction progress dialog does **not** have a cancel button and cannot be cancelled via ESC.
* I tested that the randomization progress dialog has a cancel button.
* I tested that pressing …

Allow cleanly cancelling randomization

---

checks.yaml

Fixes a bug where, after raising the shark's head, the nose rupee wouldn't appear on the pillar nearest the bird statue.
I raised the shark's head and confirmed the rupee was missing. I loaded my save after applying the patch and the rupee check appeared.

Fix pirate nose rupee not appearing after raising the shark head

---

patches.yaml

Removes the following cutscenes
- Flip over lilypad after gutters in AC (more relevant now with the Rupee Under Lilypad check)
- All Sandship floor switch first-time raise/lower cutscenes
- Sandship generator activation cutscenes
I've verified that all these cutscenes are actually removed

Remove some ac and ssh cutscenes

---

music.yaml

Fixes the types for some songs that caused incorrect behavior with music rando
- Skyview is now of type 7 (3 streams, additive) -- fixes the issue of the middle of skyview being very loud with certain music rando
- Ancient Cistern is now of type 4 (2 streams, standard) -- fixes the issue of incorrect behavior with the basement music
- Lake Floria is now of type 6 (3 streams, standard) -- fixes the issue of the music going away while underwater
- Sailing the Sand Sea is now of type 7 (3 streams, additive) -- fixes the issue of the music being very loud when near enemies

Fix incorrectly labeled songs

---

patches.yaml

Patches the loadzone into Boko Base Volcano Summit to be in the same position as the Eldin Volcano Volcano Summit loadzone. Should make it impossible to perform the precise jumpslash over the Fi trigger preventing access without Fireshield Earrings
I tested to going through the loadzone from multiple angles and positions and it seems to be the same as the Eldin Volcano equivalent now. I don't know the setup for the trick so I didn't test that but the patch functionally works as expected :p

Move boko base vc loadzone

---

logic/logic_input.py
logic/randomize.py

When using Starting Entrance Rando with Any or Any Surface Region, some areas are significantly more likely to be chosen because they have many dense entrances, e.g. Faron (Great Tree), Skyloft (all the house doors). This PR changes the weights so that entrances in regions with many entrances are significantly less likely to be picked and entrances in regions with few entrances are more likely to be picked, resulting in a more uniform choice of starting region.
I generated a bunch of (dry run) seeds.
I added some debug logging to verify that this makes Skyloft entrances less common.

Weighted Starting Entrance Rando for fewer Skyloft starts

---

.gitignore

VS Code / ripgrep's search is `.gitignore`-aware, so the rule above the added line excludes some legitimate source files. This adds an override for some actual source files that would otherwise be hidden from search tools.
VS Code search now finds the implementation of e.g. `fix_freestanding_item_y_offset`.
The offending rule could also be made more specific if someone knows what files it's meant to match in the first place.

Prevent .gitignore from excluding custom_symbols/funcs from search tools

---

options.py
ssrando.py

The output path setting is now only validated upon randomization (if dry-run is off). This prevents the unexpected behavior that can result if a user generates directly to USB and then subsequently removes the USB, thereby preventing any future settings changes from saving as it constantly errors on saving the output path. It also means that this output path will remain when loaded from settings if the USB drive is not connected. 
I tried to generate to my USB without being connected, and it threw an error before randomization. I was still able to get a spoiler log with a dry run. I also launched the rando with said path in my settings file and it kept the path there.

Prevent Setting Errors from Invalid Output Path

---

patches.yaml

Removes some Zelda/Propeller Dowsing targets in Mogma Turf that caused phantom pings, particularly in the upper regions of the area.
I generated a seed with no pinging chests in Mogma Turf, ventured over there, dowsed all around the area, and got no pings.
These were just targets I must have missed when going through and removing them when preparing for chest dowsing.

Remove stray top-slot dowsing targets in mogma turf

---

patches.yaml

Lopsa, Erla, and Oolo are available from the start in Faron Woods. They can be saved before Machi -- saving Machi spawns Bucha, allowing you to collect the reward.
I generated a new seed with the patches and was able to save the other Kikwis, then save Machi, then collect the reward.
Ported from HD Rando, with object IDs adjusted to line up correctly.

Allow saving the other Kikwis before Machi (HDR port)

---

patches.yaml

Removes some arcs from eldin to make it less likely to crash
Make sure eldin still works and I didn't delete something important by accident
It's still possible for eldin to crash, but that can't be fixed without dynamically loading item arcs

remove unnecessary arcs from eldin

---

CHANGELOG.md
eventpatches.yaml
patches.yaml

#BringBackImp2
- Removes Groose's text regarding the Groosenator prior to the imp 2 fight
- Impa's text teleports Link directly to the sealed temple after killing imp 2, removing the need to skyward strike the spile 
Turn off skip imp2 :)

Imp 2 cutscene improvements

---

gui/dialogs/custom_theme/ui_custom_theme_dialog.py
gui/dialogs/tricks/ui_tricks_dialog.py
gui/randogui.ui
gui/ui_randogui.py

This moves all the QSpinBox elements below their respective QLabel so they can take the whole width of their column to properly display their value.
Only by launching the rando app, given this is only UI changes. 
This has already been tested by someone who had issues before.

Improve element layout for better counter legibility

---

checks.yaml
eventpatches.yaml
patches.yaml

Since Relic scene flags were delegated from 102-111, Relic 1 in Eldin Trial would disappear after the first load, as its flag (102) is shared by the flag set at the start of the trial. This offsets all flags by 1 to fix this issue.
I loaded into each silent realm, verifying that none of the scene flags set collided with a relic's scene flag, and verified that no items disappeared after a reload.
Also sets the intro text flags as startflags for each silent realm, skipping the Spirit Vessel animation & question prompt

Fix Flag Collision w/ Eldin Trial Relic 1

---

dump.yaml
logic/requirements/Lanayru.yaml
logic/requirements/Sandship.yaml

The exit "Ship's Bow" -> "Before Ship's Bow" is meant to require defeating Scervo and opening the Chest, but "Chest" here resolves to the Lanayru Caves chest, which causes seed generation to error out with "Cannot ban potentially inlined away requirement \Lanayru\Caves\Chest". This fixes the dependency to require defeating Scervo instead
- Tracker logic seems unchanged
- Generating a seed with Lanayru Caves Chest banned still works
- Maybe it'd be useful to catch and reject these errors at logic parse time

Fix Lanayru Caves Chest being unbannable

---

dump.yaml
entrances.yaml
logic/logic_input.py
logic/requirements/Lanayru.yaml

The fundamental code changes and what they translate to functionally.
When an element in logic files is ambiguous, the parser will refuse it.
This also makes the lookup function clearer in code.
Caveats: some ambiguity is still allowed.
- If the name refers to something present in the same node, ambiguity is not checked (eg. if B requires A and A is already a location in the current node)
- If the element is not found at or below the current node, the search happens again at its parent, etc. So, if the element is ambiguous at the root but not where it's found, then it's fine

Remove and disallow ambiguity in logic files

---

logic/randomize.py

With Limit Start Entrance and fewer than 3 starting tablets, surface entrances
for a given seed are less likely compared to always available entrances in The Sky,
so proportionally increase the chance of a surface entrance to adjust for
the unavailable provinces. This makes spawns more uniform across seeds.
See https://discord.com/channels/1149716173613707287/1196600771068825711/1306426162922258454
Effectively reduces the chance of a vanilla spawn in the weekly settings from ~18.8% to ~7.3%.
Generate 10000 random entrances with:
* The weekly settings
* 0 starting tablets
* Limit Starting Entrance off
This behavior has always existed, but it is exacerbated by the combination of Any Surface Region + Limit Starting Entrance + #571.

Prevent Limit Starting Entrance from choosing Sky entrances too often

---

brresTools/brres.py

- Adds External Folder support to brres.py
- Adds the `get_all_paths` for brres files
- slightly changes the name reading since the string pool gives the size of the string (no loop search for null term required)
brres modification *should* remain untouched. if texture replacement still works, this should be good to go.
Only reason I wanted to update here is for any other program that may reference this file to do something.

update brres.py to support extracting External data
